version: "3.9"

services:
  subdomain-tcp-proxy:
    container_name: subdomain-tcp-proxy
    privileged: true
    build:
      context: ../
      dockerfile: ./Dockerfile # context 경로 기준 상대경로
    volumes: # docker-comose 파일 경로 기준 상대 경로
      - ../:/workdir
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: /bin/sh
